
# ******************************************************************************
# *                                                                            *
# *                           settings.py                              *
# *                        Please DO NOT edit this file.                       *
# *   If you need change settings, please edit in local_settings.py.   *
# *                                                                            *
# * How to change settings:                                                    *
# * copy the setting you need change and paste into local_settings.py  *
# * change the value according to instructions                                 *
# * save the local_settings.py file                                    *
# * use batch.py                                                                *
# ******************************************************************************

import os

"""
    Path to the Maya exe.
"""
MAYA_EXE_PATH = "D:\Program Files\Autodesk\Maya2019\bin\maya.exe"

"""
    Import Settings

"""
IMPORT_FILETYPE = "fbx" # filetype to import.

"""
    Export Settings

"""
EXPORT_PATH = ""
EXPORT_FILETYPE = 'fbx'

"""
    run the main.py on Animations?
    True: will fix the root node and copy the keys of the existing animation.
    False: will only fix the root node.
"""
IS_ANIMATION = True

SAVE = False # save a Maya file?